### PR TITLE
Update paper.md

### PR DESCRIPTION
**Pull request by danielskatz**

### CODE REVIEW

**Comment by domschrei** [comment]
Thank you for the corrections!

Regarding the ERC logo, this is technically a requirement from our funding (see https://erc.europa.eu/managing-your-project/communicating-your-research -  "How to acknowledge the ERC funding?"). We also included this graphic in the acknowledgment sections of the related publications (SAT'21, Euro-Par'22). So could we please keep the graphic in the paper?

**Comment by danielskatz** [comment]
This seems really unusual to me, and I don't think large publishers would allow it. Can you show me an example of this in a Nature paper, for example, or one from another large publisher?

**Comment by domschrei** [comment]
The papers where we did this are published by Springer. I can't provide another example without searching for one first. 

This is how we've interpreted the referenced funding guidelines. But if the paper won't be accepted like this then I guess I'll omit the logo and assume that it's fine with just the textual acknowledgment.

**Comment by danielskatz** [comment]
ok, I've remove the figure deletion from this PR

**Comment by domschrei** [comment]
Thanks a lot! I am merging it.

**Pull request merged**
